version: 2
jobs:
  build:
    docker:
      - image: minepicco/cci-aws:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: aws configure
          command: |
            mkdir .aws
            touch ./aws/config
            echo "[default]" > ./aws/config
            echo "output = json" >> ./aws/config
            echo "region = "$aws_region >> ./aws/config
            touch ./aws/credentials
            echo "[default]" > ./aws/credentials
            echo "aws_access_key_id = "$aws_keyid >> ./aws/credentials
            echo "aws_secret_access_key = "$aws_key >> ./aws/credentials
            chmod 600 ./aws/*
      - run:
          name: curl test
          command: curl http://ec2-18-191-70-3.us-east-2.compute.amazonaws.com 
      - run:
          name: get gip
          command: gip=`curl -X GET https://api.ipify.org` && echo "Global IPアドレス："$gip
      - run:
          name: echo gip again
          command: |
            gip=`curl -X GET https://api.ipify.org`
            echo "Global IPアドレス："$gip
      - run:
          name: add rule
          command: |
            gip=`curl -X GET https://api.ipify.org`
            aws ec2 authorize-security-group-ingress --group-name cci-test --protocol tcp --port 80 --cidr $gip"/32"
      - run:
          name: curl test
          command: curl http://ec2-18-191-70-3.us-east-2.compute.amazonaws.com
      - run:
          name: remove rule
          command: |
            gip=`curl -X GET https://api.ipify.org`
            aws ec2 authorize-security-group-ingress --group-name cci-test --protocol tcp --port 80 --cidr $gip"/32"
