version: 2
jobs:
  build:
    docker:
      - image: macnicadevops/cci-build-aws:1.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: aws configure
          command: |
            aws configure set region $region
            aws configure set aws_access_key_id $aws_keyid
            aws configure set aws_secret_access_key $aws_key
            aws configure set output json
      - run:
          name: get 
          command: |
            gip=`curl -X GET https://api.ipify.org`
            aws ec2 authorize-security-group-ingress --group-name $sg_name --protocol tcp --port $port --cidr $gip"/32" 
            curl -k -u $cred -H 'Content-Type: application/json' -X GET https://$tw_url/api/v1/registry?imageID=$image_id  | jq
            aws ec2 revoke-security-group-ingress --group-name $sg_name --protocol tcp --port $port --cidr $gip"/32" 
